discord-invite: "discord.gg/invite"
joinMessage: "%player% joined the game"
leftMessage: "%player% left the game"
antiIllegals:
   removeIllegalEnchantaments: true
   removeOverStackedItems: true
   removeIllegalPotions: true
   inventoryOpenEvent: true
   inventoryCloseEvent: true
   removeIllegalItems: true
   blockPlaceEvent: true
   pickupItemEvent: true
   PotionSplashEvent: true
   bowEvent: true
   maxItemDamage: 36
   maxPotionLevel: 5
   maxBowDamage: 36