name: ServerCore
main: me.yailya.servercore.Main
version: 1.1
authors: [ ya-ilya ]
commands:
   discord:
      description: Tells you an invite to discord server
   stats:
      description: Tells you the world size, and the number of players joined on to the server
   message:
      description: Sends a private message to the specified player.
      aliases: [ msg, w, tell, t, pm ]
   reply:
      description: Quickly reply to the last player to message you.
      aliases: [ r ]
   ignore:
      description: Ignore or unignore other players.
   ignorelist:
      description: tells you the list of players you ignore
   uptime:
      description: Tells you how much time has passed without restarting the server
   ping:
      description: Tells you ping of the specified player
   bed:
      description: Tells you your bed location
   joindate:
      description: Tells you player join date
      aliases: [ jd ]
   kill:
      description: Kills you
      aliases: [ suicide ]